<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateDataKunjungansTable extends Migration
{
    public function up()
    {
        Schema::create('data_kunjungans', function (Blueprint $table) {
            $table->bigIncrements('id');
            //Mancanegara
            $table->integer('asean')->nullable();
            $table->integer('malaysia')->nullable();
            $table->integer('filipina')->nullable();
            $table->integer('singapura')->nullable();
            $table->integer('thailand')->nullable();
            $table->integer('vietnam')->nullable();
            $table->integer('aseanlainnya')->nullable();
            $table->integer('asia')->nullable();
            $table->integer('hongkong')->nullable();
            $table->integer('india')->nullable();
            $table->integer('jepang')->nullable();
            $table->integer('korea_selatan')->nullable();
            $table->integer('taiwan')->nullable();
            $table->integer('tiongkok')->nullable();
            $table->integer('timor_leste')->nullable();
            $table->integer('asia_lainnya')->nullable();
            $table->integer('timur_tengah')->nullable();
            $table->integer('arab_saudi')->nullable();
            $table->integer('kuwait')->nullable();
            $table->integer('mesir')->nullable();
            $table->integer('uae')->nullable();
            $table->integer('yaman')->nullable();
            $table->integer('timur_tengah_lain')->nullable();
            $table->integer('eropa')->nullable();
            $table->integer('perancis')->nullable();
            $table->integer('jerman')->nullable();
            $table->integer('belanda')->nullable();
            $table->integer('inggris')->nullable();
            $table->integer('rusia')->nullable();
            $table->integer('eropa_lainnya')->nullable();
            $table->integer('amerika')->nullable();
            $table->integer('amerika_serikat')->nullable();
            $table->integer('kanada')->nullable();
            $table->integer('brazil')->nullable();
            $table->integer('meksiko')->nullable();
            $table->integer('amerika_lainnya')->nullable();
            $table->integer('oseania')->nullable();
            $table->integer('australia')->nullable();
            $table->integer('selandia_baru')->nullable();
            $table->integer('papua_nugini')->nullable();
            $table->integer('oseania_lainnya')->nullable();
            $table->integer('afrika')->nullable();
            $table->integer('afrika_selatan')->nullable();
            $table->integer('afrika_lainnya')->nullable();
            $table->integer('total_mancanegara')->nullable();
            //Nusantara
            $table->integer('jawa')->nullable();
            $table->integer('jawa_timur')->nullable();
            $table->integer('jawa_barat')->nullable();
            $table->integer('jawa_tengah')->nullable();
            $table->integer('diy')->nullable();
            $table->integer('dki')->nullable();
            $table->integer('banten')->nullable();
            $table->integer('kalimantan')->nullable();
            $table->integer('kaltim')->nullable();
            $table->integer('kalteng')->nullable();
            $table->integer('kalbar')->nullable();
            $table->integer('kalsel')->nullable();
            $table->integer('kaltara')->nullable();
            $table->integer('sumatera')->nullable();
            $table->integer('aceh')->nullable();
            $table->integer('sumut')->nullable();
            $table->integer('riau')->nullable();
            $table->integer('kep_riau')->nullable();
            $table->integer('jambi')->nullable();
            $table->integer('sumbar')->nullable();
            $table->integer('sumsel')->nullable();
            $table->integer('bangka')->nullable();
            $table->integer('bengkulu')->nullable();
            $table->integer('lampung')->nullable();
            $table->integer('sulawesi')->nullable();
            $table->integer('sulut')->nullable();
            $table->integer('sulbar')->nullable();
            $table->integer('sulteng')->nullable();
            $table->integer('sulsel')->nullable();
            $table->integer('sulgara')->nullable();
            $table->integer('gorontalo')->nullable();
            $table->integer('bali_nustra')->nullable();
            $table->integer('bali')->nullable();
            $table->integer('ntb')->nullable();
            $table->integer('ntt')->nullable();
            $table->integer('papuaa')->nullable();
            $table->integer('maluku')->nullable();
            $table->integer('maluku_utara')->nullable();
            $table->integer('papua')->nullable();
            $table->integer('papua_barat')->nullable();
            $table->integer('papua_baratdaya')->nullable();
            $table->integer('papua_selatan')->nullable();
            $table->integer('papua_tengah')->nullable();
            $table->integer('papua_pegunungan')->nullable();
            $table->integer('total_nusantara')->nullable();
            $table->date('start_date');
            $table->date('end_date');
            $table->timestamps();
            $table->softDeletes();
        });
    }
}
